name       : packer
version    : 1.3.5
release    : 6
source     :
    - https://github.com/hashicorp/packer/archive/v1.3.5.tar.gz : 91f7da67b2390704c6bdeb14b33ddc4abb192c044fc789ce6be45b9fda3d425e
license    : MPL-2.0
component  : programming.tools
summary    : Packer is a tool for building identical machine images for multiple platforms from a single source configuration.
description: |
    Packer is a tool for building identical machine images for multiple platforms from a single source configuration.

    Packer is lightweight, runs on every major operating system, and is highly performant, creating machine images for multiple platforms in parallel. Packer comes out of the box with support for many platforms, the full list of which can be found at https://www.packer.io/docs/builders/index.html.

    Support for other platforms can be added via plugins.

    The images that Packer creates can easily be turned into Vagrant boxes.
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/hashicorp
    export GOPATH=`pwd`
    ln -sv `pwd` src/github.com/hashicorp/packer
    cd src/github.com/hashicorp/packer
    go build -o packer-binary
install    : |
    cd src/github.com/hashicorp/packer
    install -Dm 00755 packer-binary $installdir/usr/bin/packer
